x1 = int(input("valor de x1:"))
if x1 > 3.77:
    print("Opção 1")

else:
    x2 = int(input("valor de x2:"))
    
    if x2 > 0.5:
        x3 = int(input("valor de x3:"))
        
        if x3 >= 0.78:
            print("Opção 2")
        
        else:
            print("Oção 1")
    
    else:
        x4 = int(input("valor de x4:"))
            
        if  x4 < 0.5 and x4 > 0.25:
            print ("Opção 1")
        
        elif x4 == 0.5:
            print ("Opção 3")
            
        elif x4 > 0.5 or x4 <= 0.25:
            print ("Opção 2")

 

    
